# Goal: Track and respond to specific pull request lifecycle events.

name: PR Lifecycle Evevnts

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]

jobs:
    track-pr-events:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR Details
              env:
                ACTION_TYPE: ${{ github.event.action }}
                PR_TITLE: ${{ github.event.pull_request.title }}
                PR_AUTHOR: ${{ github.event.pull_request.user.login }}
                HEAD_REF: ${{ github.head_ref }}
                BASE_REF: ${{ github.base_ref }}
              run: |
                echo "Event Type: $ACTION_TYPE"
                echo "PR Title: $PR_TITLE"
                echo "PR Author: $PR_AUTHOR"
                echo "Source Branch (Head): $HEAD_REF"
                echo "Target Branch (Base): $BASE_REF"

            - name: Congratulative on Merge
              # This step only runs if the pr was closed AND successfully merged
              if: github.event.pull_request.merged == true
              run: |
                echo "🎉 Congratulations! The PR has been successfully merged into ${{ github.base_ref }}."
