# Goal: Securely pass GitHub Secrets to a runner step using Environment Variables.

name: Day 44 - Task 2 Env Secrets

on:
    workflow_dispatch:

jobs:
    env-secret-job:
        runs-on: ubuntu-latest
        steps:
            - name: Verify secrets as environment variables
              env:
                MY_ENV_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
                DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}

              run: |
                  echo "=== Verifying Secrets via Environment Variables ==="
                
                  # Using bash variable syntax ($) instead of GitHub context syntax ($#{{ }}) to access secrets as environment variables
                  if [ -n "$MY_ENV_SECRET" ]; then
                      echo "Success: MY_ENV_SECRET is securely loaded into runner memory!"
                  else
                      echo "Error: MY_ENV_SECRET is missing!"
                  fi

                  if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_PASS" ]; then
                      echo "Success: Docker credentials are ready for Day 45 Docker login!"
                  else
                      echo "Warning: Docker credentials are missing!, Please add them in GitHub Secrets.""
                  fi