# Goal: Demonstrate how GitHub Actions securely handles and masks sensitive data.

name: Day 44 - Task 1 Secrets 

on:
    workflow_dispatch:

jobs:
    secret-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Verify and Print Secret
              run: |
                # 1. Sefley check if secret exists (Best Practice)
                if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                    echo "The secret is set: true"
                else
                    echo "The secret is missing!"
                fi

                # 2. Intentionally print it to see GitHub's masking feature in action 
                echo "Trying to print directly: ${{ secrets.MY_SECRET_MESSAGE }}"
                